Feat/crud clinics
PhuTam54/ecommerceTASC-BE pull request #7
Opened 2024-05-25 10:47 UTC by Nam090802

- implement lại clinic service
- fix addClinic func 
- delete func convertToDTO và func convertToEntity

2024-05-27 15:42 UTC, PhuTam54 approved these changes

2024-05-27 15:43 UTC, NguyenHoangHiep28 requested changes

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/controller/ClinicController.java
> +    private ClinicServiceImpl clinicService;
private ClinicService clinicService;

Đã viết interface thì khi inject khai báo interface chứ không phải implementation 

Ngoài ra khuyến nghị sử dụng constructor injection hơn field injection

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/service/impl/ClinicServiceImpl.java
> +    public List<Clinic> getAllClinics() {
Cần thêm phân trang !

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/service/impl/ClinicServiceImpl.java
> +    public List<Clinic> getClinicByAddress (String address) {
Truyền vào 1 DTO tìm kiếm theo điều kiện clinicName, address, phone, Email, openingHours, closing_hours, phân trang

Sử dụng specification hoặc Criteria API

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/service/impl/ClinicServiceImpl.java
> +        Clinic clinic = clinicMapper.clinicDTOToClinic(clinicDTO);
Xem lại business add Clinic check trùng clinicName, Phone, email ?

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/service/impl/ClinicServiceImpl.java
> +        }
Recommend đẩy clause check lỗi lên đầu (guard clause) nếu lỗi thì return hoặc throw luôn, nếu ko lỗi thì xử lý tiếp, tránh if-else hell
FYI: https://deviq.com/design-patterns/guard-clause

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/service/impl/ClinicServiceImpl.java
> +        }
guard clause + xóa mềm (thêm trường is_deleted hoặc is_inactive khi xóa thì set trường này giá trị là 1, default là 0) 
FYI: https://www.baeldung.com/spring-jpa-soft-delete

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/resources/application.properties
> +spring.datasource.password=Nam09082002@
File cấu hình thông thường sẽ để là cấu hình chung trên môi trường staging, UAT, production ... không đẩy cấu hình local lên trên git repo

2024-05-27 15:43 UTC, NguyenHoangHiep28 commented on src/main/java/com/example/ecommercebe/controller/ClinicController.java
> +        List<Clinic> clinics = clinicService.getAllClinics();
Thêm phân trang

2024-05-28 02:58 UTC, Nam090802 commented on src/main/java/com/example/ecommercebe/controller/ClinicController.java
> +    private ClinicServiceImpl clinicService;
resolved

2024-05-28 02:59 UTC, Nam090802 commented on src/main/java/com/example/ecommercebe/service/impl/ClinicServiceImpl.java
> +    public List<Clinic> getAllClinics() {
resolved

2024-05-28 04:12 UTC, merged